import crypto from "node:crypto";
import { getDb, requireUser, serverTimestamp } from "./firebaseAdmin.js";
import { writeAdminActivityLog } from "./adminAuth.js";

const CHANNELS = ["in_app", "email", "whatsapp", "telegram"];
const VALID_TYPES = new Set(["payment_initiated","payment_successful","payment_failed","payment_cancelled","payment_pending","payment_verification_delayed","subscription_activated","subscription_granted","subscription_extended","subscription_expiring_7_days","subscription_expiring_3_days","subscription_expiring_1_day","subscription_expired","refund_initiated","refund_completed","refund_failed","target_published","resource_published","class_scheduled","class_reminder","class_changed","class_cancelled","recording_available","announcement","admin_support_reply","test_notification"]);
const TRANSACTIONAL_TYPES = new Set(["payment_initiated","payment_successful","payment_failed","payment_cancelled","payment_pending","payment_verification_delayed","subscription_activated","subscription_granted","subscription_extended","subscription_expiring_7_days","subscription_expiring_3_days","subscription_expiring_1_day","subscription_expired","refund_initiated","refund_completed","refund_failed","admin_support_reply","test_notification"]);
const TEMPLATE_FIELDS = ["studentName","planName","durationLabel","amount","currency","orderId","paymentDate","accessStartAt","accessEndAt","referenceId","replyText","contentTitle","classDate"];
const RESEND_ENDPOINT = "https://api.resend.com/emails";
const SUPPORT_EMAIL = "support@delightguidance.com";
const MAX_ATTEMPTS = 5;
const RETRYABLE = new Set(["failed","retryable","retry_scheduled"]);

function clean(v,n=500){return String(v||"").trim().slice(0,n)}
function internalUrl(v){const s=clean(v,500);return s.startsWith("/")&&!s.startsWith("//")?s:"/student-desk"}
function docId(key){return crypto.createHash("sha256").update(key).digest("hex")}
function iso(v){return v?.toDate?v.toDate().toISOString():v instanceof Date?v.toISOString():v||null}
function safe(id,d={}){return{id,eventType:d.eventType,title:d.title,message:d.message,destination:d.destination,priority:d.priority||"normal",readAt:iso(d.readAt),createdAt:iso(d.createdAt),expiresAt:iso(d.expiresAt),related:d.related||{},channels:d.channels||{}}}
function fail(statusCode,message,code="NOTIFICATION_ERROR"){const error=new Error(message);error.statusCode=statusCode;error.code=code;throw error}
function safeTemplateData(value={}){return Object.fromEntries(TEMPLATE_FIELDS.map(key=>[key,clean(value[key],key==="replyText"?5000:300)]).filter(([,item])=>item))}
export function isValidEmail(value){const email=clean(value,254),at=email.indexOf("@"),domain=email.slice(at+1);return email.length<=254&&at>0&&at===email.lastIndexOf("@")&&domain.includes(".")&&!email.split("").some(char=>char.trim()==="")}
export function escapeEmailHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]))}
export function classifyResendFailure(status=0,code=""){const permanent=[400,401,403,404,422].includes(Number(status))||["invalid_to_address","validation_error","restricted_api_key"].includes(String(code));return{retryable:!permanent,status:permanent?"permanent_failure":"failed"}}

export function providerStatus(){
 return {in_app:{enabled:true,status:"ready",provider:"internal"},email:{enabled:Boolean(process.env.RESEND_API_KEY&&process.env.NOTIFICATION_FROM_EMAIL),status:process.env.RESEND_API_KEY&&process.env.NOTIFICATION_FROM_EMAIL?"configured":"configuration_required",provider:"resend",required:["RESEND_API_KEY","NOTIFICATION_FROM_EMAIL"]},whatsapp:{enabled:false,status:"configuration_required",provider:"meta_cloud_api",required:["WHATSAPP_ACCESS_TOKEN","WHATSAPP_PHONE_NUMBER_ID","WHATSAPP_VERIFY_TOKEN"]},telegram:{enabled:false,status:"configuration_required",provider:"telegram",required:["TELEGRAM_BOT_TOKEN","TELEGRAM_BOT_USERNAME","TELEGRAM_CONNECTION_SECRET"]}};
}

function formatEmailDate(value){if(!value)return"Not available";const date=new Date(value);return Number.isNaN(date.getTime())?clean(value,120):new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(date)}
function money(value,currency="INR"){const number=Number(value);return Number.isFinite(number)?new Intl.NumberFormat("en-IN",{style:"currency",currency:clean(currency,3)||"INR"}).format(number):"Not available"}
function row(label,value){return `<tr><td style="padding:8px 12px;color:#526079;border-bottom:1px solid #e5eaf2;width:38%">${escapeEmailHtml(label)}</td><td style="padding:8px 12px;color:#111c3a;border-bottom:1px solid #e5eaf2;overflow-wrap:anywhere">${escapeEmailHtml(value||"Not available")}</td></tr>`}
function emailCopy(notification){
 const data=notification.templateData||{},type=notification.eventType,name=data.studentName||"Student",plan=data.planName||"your plan";
 if(type==="payment_successful")return{subject:`Payment successful - ${plan}`,heading:"Payment successful",intro:`Hello ${name}, your payment has been verified successfully.`,rows:[["Plan",plan],["Duration",data.durationLabel],["Amount",money(data.amount,data.currency)],["Order ID",data.orderId],["Payment date",formatEmailDate(data.paymentDate)],["Access starts",formatEmailDate(data.accessStartAt)],["Access ends",formatEmailDate(data.accessEndAt)]]};
 if(type==="subscription_activated")return{subject:`Your ${plan} access is active`,heading:"Subscription activated",intro:`Hello ${name}, your Delight Banking access is now active.`,rows:[["Plan",plan],["Duration",data.durationLabel],["Access starts",formatEmailDate(data.accessStartAt)],["Access ends",formatEmailDate(data.accessEndAt)]]};
 if(type==="payment_failed")return{subject:"Payment was not completed",heading:"Payment unsuccessful",intro:`Hello ${name}, we could not confirm your payment. Your account and any existing access are unchanged.`,rows:[["Plan",plan],["Order ID",data.orderId]]};
 if(type==="payment_cancelled")return{subject:"Payment was cancelled",heading:"Payment cancelled",intro:`Hello ${name}, the payment attempt was cancelled and no new access was activated.`,rows:[["Plan",plan],["Order ID",data.orderId]]};
 if(type==="payment_pending")return{subject:"Payment confirmation is pending",heading:"Payment pending",intro:`Hello ${name}, payment confirmation is taking longer than expected. Please do not pay again while verification continues.`,rows:[["Plan",plan],["Order ID",data.orderId]]};
 if(type==="subscription_expired")return{subject:`${plan} access has expired`,heading:"Subscription expired",intro:`Hello ${name}, your recorded access period has ended.`,rows:[["Plan",plan],["Access ended",formatEmailDate(data.accessEndAt)]]};
 if(type.startsWith("subscription_expiring_"))return{subject:`${plan} access expires soon`,heading:"Subscription expiry reminder",intro:`Hello ${name}, your current access period is approaching its expiry date.`,rows:[["Plan",plan],["Access ends",formatEmailDate(data.accessEndAt)]]};
 if(type==="resource_published")return{subject:`New resource: ${data.contentTitle||notification.title}`,heading:"New resource assigned",intro:`Hello ${name}, a new learning resource is available for your plan.`,rows:[["Resource",data.contentTitle||notification.title]]};
 if(type==="target_published")return{subject:`New target: ${data.contentTitle||notification.title}`,heading:"New target assigned",intro:`Hello ${name}, a new preparation target has been assigned.`,rows:[["Target",data.contentTitle||notification.title]]};
 if(["class_scheduled","class_changed","class_reminder"].includes(type))return{subject:`Class update: ${data.contentTitle||notification.title}`,heading:"Class update",intro:`Hello ${name}, there is an update to a class assigned to your plan.`,rows:[["Class",data.contentTitle||notification.title],["Date",formatEmailDate(data.classDate)]]};
 if(type==="admin_support_reply")return{subject:`Re: Your Delight Banking enquiry [${data.referenceId||"reference"}]`,heading:"Reply from Delight Banking support",intro:`Hello ${name}, our support team has replied to your enquiry.`,body:data.replyText,rows:[["Reference",data.referenceId]]};
 return{subject:clean(notification.title,180)||"Delight Banking account update",heading:clean(notification.title,180)||"Account update",intro:`Hello ${name}, ${clean(notification.message,1000)}`,rows:[]};
}
export function buildEmailTemplate(notification){
 const copy=emailCopy(notification),destination=internalUrl(notification.destination),url=`https://www.delightguidance.com${destination}`,body=copy.body?`<div style="white-space:pre-wrap;padding:16px;background:#f7f9fc;border-radius:8px;color:#111c3a">${escapeEmailHtml(copy.body)}</div>`:"";
 const html=`<!doctype html><html><body style="margin:0;background:#f2f5fa;font-family:Arial,sans-serif;color:#111c3a"><div style="display:none;max-height:0;overflow:hidden">${escapeEmailHtml(copy.intro)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f2f5fa"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border:1px solid #dce4ef;border-radius:12px"><tr><td style="padding:24px;background:#0b1736;color:#fff;border-radius:12px 12px 0 0"><strong style="font-size:20px">Delight Banking</strong><div style="font-size:13px;color:#cbd8f4;margin-top:4px">Delight Guidance</div></td></tr><tr><td style="padding:28px 24px"><h1 style="font-size:25px;line-height:1.25;margin:0 0 16px">${escapeEmailHtml(copy.heading)}</h1><p style="line-height:1.65;margin:0 0 20px">${escapeEmailHtml(copy.intro)}</p>${body}${copy.rows.length?`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:20px 0;border:1px solid #e5eaf2;border-radius:8px">${copy.rows.map(([a,b])=>row(a,b)).join("")}</table>`:""}<a href="${escapeEmailHtml(url)}" style="display:inline-block;background:#185adb;color:#fff;text-decoration:none;font-weight:bold;padding:12px 18px;border-radius:8px">Open Student Desk</a><p style="font-size:14px;line-height:1.6;color:#526079;margin:24px 0 0">Need help? Email <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a>.</p></td></tr><tr><td style="padding:18px 24px;background:#f7f9fc;color:#667085;font-size:12px;line-height:1.5;border-radius:0 0 12px 12px">This email relates to your Delight Guidance account or enquiry. Transactional messages contain no promotional subscription.</td></tr></table></td></tr></table></body></html>`;
 const lines=[copy.heading,"",copy.intro,"",...(copy.body?[copy.body,""]:[]),...copy.rows.map(([a,b])=>`${a}: ${b||"Not available"}`),"",`Open Student Desk: ${url}`,`Support: ${SUPPORT_EMAIL}`,"","This email relates to your Delight Guidance account or enquiry."];
 return{subject:clean(copy.subject,180),html,text:lines.join("\n")};
}

async function emailPreference(uid,eventType){
 if(TRANSACTIONAL_TYPES.has(eventType))return true;
 if(!uid)return false;
 const snap=await getDb().collection("notificationPreferences").doc(uid).get(),preferences=snap.exists?snap.data():{};
 if(eventType==="announcement")return preferences.marketing===true;
 if(eventType==="resource_published")return preferences.resourceNotifications!==false;
 if(eventType==="target_published")return preferences.targetReminders!==false;
 if(eventType.startsWith("class_")||eventType==="recording_available")return preferences.classNotifications!==false;
 return preferences.transactionalEmail!==false;
}

async function claimEmailDelivery(notificationId,allowedStatuses=["queued"]){
 const db=getDb(),ref=db.collection("notificationDeliveries").doc(docId(notificationId+":email"));let claimed=null;
 await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)return;const value=snap.data(),attempt=Number(value.attemptNumber||0);if(!allowedStatuses.includes(value.status)||attempt>=MAX_ATTEMPTS)return;claimed={...value,id:ref.id,attemptNumber:attempt+1};tx.set(ref,{status:"processing",attemptNumber:attempt+1,lastAttemptedAt:serverTimestamp(),updatedAt:serverTimestamp(),nextRetryAt:null,safeFailureCode:"",safeFailureMessage:""},{merge:true})});
 return claimed;
}
async function finalizeEmail(ref,notificationRef,attempt,result){
 const update={status:result.status,updatedAt:serverTimestamp(),providerMessageId:clean(result.providerMessageId,240),safeProviderResponse:result.safeProviderResponse||{},safeFailureCode:clean(result.safeFailureCode,100),safeFailureMessage:clean(result.safeFailureMessage,500),nextRetryAt:result.nextRetryAt||null};
 if(result.status==="sent"||result.status==="accepted")update.sentAt=serverTimestamp();
 else update.failedAt=serverTimestamp();
 const batch=getDb().batch();batch.set(ref,update,{merge:true});batch.set(notificationRef,{["channels.email.state"]:result.status,["channels.email.retryCount"]:attempt,["channels.email.safeFailureCode"]:update.safeFailureCode},{merge:true});await batch.commit();
}
export async function deliverNotificationEmail(notificationId,{allowedStatuses=["queued"],fetchImpl=fetch,timeoutMs=8000}={}){
 const config=providerStatus().email,db=getDb(),notificationRef=db.collection("notifications").doc(clean(notificationId,200)),deliveryRef=db.collection("notificationDeliveries").doc(docId(notificationId+":email"));
 if(!config.enabled){await finalizeEmail(deliveryRef,notificationRef,0,{status:"configuration_required",safeFailureCode:"CONFIGURATION_REQUIRED",safeFailureMessage:"Provider configuration is required."});return{status:"configuration_required",deliveryId:deliveryRef.id}}
 const claimed=await claimEmailDelivery(notificationId,allowedStatuses);if(!claimed)return{status:"not_claimed",deliveryId:deliveryRef.id};
 const notificationSnap=await notificationRef.get();if(!notificationSnap.exists){await finalizeEmail(deliveryRef,notificationRef,claimed.attemptNumber,{status:"permanent_failure",safeFailureCode:"NOTIFICATION_NOT_FOUND",safeFailureMessage:"Notification record is unavailable."});return{status:"permanent_failure",deliveryId:deliveryRef.id}}
 const notification={id:notificationSnap.id,...notificationSnap.data()};
 if(!isValidEmail(notification.recipientEmail)){await finalizeEmail(deliveryRef,notificationRef,claimed.attemptNumber,{status:"permanent_failure",safeFailureCode:"INVALID_RECIPIENT",safeFailureMessage:"Recipient email is invalid."});return{status:"permanent_failure",deliveryId:deliveryRef.id}}
 const template=buildEmailTemplate(notification),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);
 try{
  const response=await fetchImpl(RESEND_ENDPOINT,{method:"POST",headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,"Content-Type":"application/json","Idempotency-Key":claimed.idempotencyKey},body:JSON.stringify({from:process.env.NOTIFICATION_FROM_EMAIL,to:[notification.recipientEmail],reply_to:SUPPORT_EMAIL,subject:template.subject,html:template.html,text:template.text}),signal:controller.signal});
  const data=await response.json().catch(()=>({}));if(!response.ok){const classified=classifyResendFailure(response.status,data?.name||data?.code),atLimit=claimed.attemptNumber>=MAX_ATTEMPTS;await finalizeEmail(deliveryRef,notificationRef,claimed.attemptNumber,{status:atLimit?"permanent_failure":classified.status,safeFailureCode:clean(data?.name||data?.code||`HTTP_${response.status}`,100),safeFailureMessage:clean(data?.message||"Email provider rejected the request.",500),nextRetryAt:classified.retryable&&!atLimit?new Date(Date.now()+Math.pow(2,claimed.attemptNumber-1)*60000):null,safeProviderResponse:{status:Number(response.status)}});return{status:atLimit?"permanent_failure":classified.status,deliveryId:deliveryRef.id}}
  await finalizeEmail(deliveryRef,notificationRef,claimed.attemptNumber,{status:"accepted",providerMessageId:data?.id,safeProviderResponse:{status:Number(response.status),accepted:true}});return{status:"accepted",deliveryId:deliveryRef.id,providerMessageId:clean(data?.id,240)}
 }catch(error){const atLimit=claimed.attemptNumber>=MAX_ATTEMPTS,timeout=error?.name==="AbortError";await finalizeEmail(deliveryRef,notificationRef,claimed.attemptNumber,{status:atLimit?"permanent_failure":"failed",safeFailureCode:timeout?"PROVIDER_TIMEOUT":"PROVIDER_NETWORK_ERROR",safeFailureMessage:timeout?"Email provider request timed out.":"Email provider request failed.",nextRetryAt:atLimit?null:new Date(Date.now()+Math.pow(2,claimed.attemptNumber-1)*60000)});return{status:atLimit?"permanent_failure":"failed",deliveryId:deliveryRef.id}
 }finally{clearTimeout(timer)}
}

export async function createNotification(input){
 if(!VALID_TYPES.has(input.eventType)||!input.uid)return null;
 const key=clean(input.idempotencyKey||[input.eventType,input.uid,input.orderId,input.subscriptionId,input.entityId].filter(Boolean).join(":"),500);if(!key)return null;
 const ref=getDb().collection("notifications").doc(docId(key)),config=providerStatus(),allowEmail=await emailPreference(input.uid,input.eventType),emailState=!allowEmail?"suppressed":config.email.enabled?"queued":"configuration_required";
 await getDb().runTransaction(async tx=>{if((await tx.get(ref)).exists)return;const channels={in_app:{state:"delivered",retryCount:0},email:{state:emailState,retryCount:0},whatsapp:{state:"configuration_required",retryCount:0},telegram:{state:"configuration_required",retryCount:0}};tx.create(ref,{eventType:input.eventType,recipientUid:input.uid,recipientEmail:clean(input.email,254),recipientMobile:clean(input.mobile,30),title:clean(input.title,180),message:clean(input.message,1200),destination:internalUrl(input.destination),priority:input.priority||"normal",related:input.related||{},templateData:safeTemplateData(input.templateData),idempotencyKey:key,channels,createdAt:serverTimestamp(),readAt:null,expiresAt:input.expiresAt||null});CHANNELS.forEach(channel=>{const deliveryId=docId(ref.id+":"+channel),state=channels[channel].state,provider=channel==="email"?"resend":channel==="whatsapp"?"meta_cloud_api":channel==="telegram"?"telegram":"internal";tx.create(getDb().collection("notificationDeliveries").doc(deliveryId),{deliveryId,notificationId:ref.id,recipientUid:input.uid,recipientEmail:channel==="email"?clean(input.email,254):"",channel,provider,templateId:input.eventType,templateVersion:2,status:channel==="in_app"?"available":state,attemptNumber:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),sentAt:null,deliveredAt:null,failedAt:null,lastAttemptedAt:null,nextRetryAt:null,safeFailureCode:state==="configuration_required"?"CONFIGURATION_REQUIRED":state==="suppressed"?"PREFERENCE_SUPPRESSED":"",safeFailureMessage:state==="configuration_required"?"Provider configuration is required.":state==="suppressed"?"Email suppressed by notification preferences.":"",providerMessageId:"",safeProviderResponse:{},idempotencyKey:key+":"+channel});});});
 if(allowEmail)await deliverNotificationEmail(ref.id).catch(()=>{});
 return ref.id;
}

export async function emitPaymentNotifications(result){
 const o=result?.order;if(!o?.userId)return;const paid=result.status==="paid",snapshot=o.trustedPlanSnapshot||{},templateData={studentName:o.studentName||o.userName||o.customerName||"",planName:snapshot.name||o.planName||"",durationLabel:snapshot.durationLabel||o.durationLabel||"",amount:o.amountInRupees||o.amount||(Number(o.amountInPaise||0)/100),currency:o.currency||"INR",orderId:o.orderId||o.internalOrderId||"",paymentDate:o.capturedAt||o.paidAt||new Date().toISOString(),accessStartAt:o.accessStartAt||result.subscription?.accessStartAt,accessEndAt:o.accessEndAt||result.subscription?.accessEndAt};
 await createNotification({eventType:paid?"payment_successful":result.status==="failed"?"payment_failed":result.status==="cancelled"?"payment_cancelled":"payment_pending",uid:o.userId,email:o.userEmail,title:paid?"Payment successful":"Payment update",message:paid?("Your payment for "+(snapshot.name||"your plan")+" was verified. Your subscription access is active."):("Payment status: "+result.status+"."),destination:"/student-desk",idempotencyKey:"payment:"+result.status+":"+o.orderId,related:{orderId:o.orderId,transactionId:o.paymentId||"",planId:o.planId||""},templateData});
 if(paid)await createNotification({eventType:"subscription_activated",uid:o.userId,email:o.userEmail,title:"Subscription activated",message:(snapshot.name||"Plan")+" access is active until "+(templateData.accessEndAt||"the recorded expiry date")+". Examination results are not guaranteed.",destination:"/student-desk",idempotencyKey:"subscription_activated:"+o.orderId+":"+o.userId,related:{orderId:o.orderId,subscriptionId:o.userId+"_"+o.variantId,planId:o.planId},templateData});
}

export async function emitContentAssignmentNotifications(kind, entityId, data = {}) {
 const mapping={resource:{eventType:"resource_published",label:"resource",destination:"/student-desk/resources/"},target:{eventType:"target_published",label:"target",destination:"/student-desk/targets/"},class:{eventType:"class_scheduled",label:"class",destination:"/student-desk/classes"}},meta=mapping[kind];
 if(!meta)return;
 const snapshot=await getDb().collection("subscriptions").where("status","==","active").limit(250).get(),planIds=new Set(data.planIds||[]),variantIds=new Set(data.variantIds||[]),seen=new Set();
 for(const doc of snapshot.docs){const sub=doc.data(),uid=clean(sub.userId||sub.uid,240),recipientEmail=clean(sub.userEmail||sub.email,254);if(!uid||seen.has(uid))continue;const assigned=data.accessScope==="all_plans"||data.accessScope==="public"||planIds.has(sub.planId)||variantIds.has(sub.variantId);if(!assigned)continue;seen.add(uid);await createNotification({eventType:meta.eventType,uid,email:recipientEmail,title:"New "+meta.label+" assigned",message:clean(data.title,180)+" is now available in your Student Desk.",destination:meta.destination+(kind==="class"?"":encodeURIComponent(entityId)),idempotencyKey:meta.eventType+":"+entityId+":"+uid,related:{entityId,planId:sub.planId||""},templateData:{studentName:sub.studentName||sub.userName||"",contentTitle:data.title,classDate:data.startAt}})}
}
export async function listUserNotifications(req,q={}){const u=await requireUser(req);const snap=await getDb().collection("notifications").where("recipientUid","==",u.uid).limit(Math.min(Number(q.limit)||50,100)).get();let items=snap.docs.map(d=>safe(d.id,d.data())).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));if(q.unread==="1")items=items.filter(x=>!x.readAt);if(q.type)items=items.filter(x=>x.eventType.startsWith(clean(q.type,40)));return{notifications:{items,total:items.length,unreadCount:items.filter(x=>!x.readAt).length}}}
export async function markNotifications(req,body={}){const u=await requireUser(req),db=getDb(),batch=db.batch();if(body.all){const s=await db.collection("notifications").where("recipientUid","==",u.uid).limit(100).get();s.docs.forEach(d=>batch.set(d.ref,{readAt:serverTimestamp()},{merge:true}));await batch.commit();return{success:true}}const ref=db.collection("notifications").doc(clean(body.notificationId,200)),snap=await ref.get();if(!snap.exists||snap.data().recipientUid!==u.uid)fail(404,"Notification not found.");await ref.set({readAt:serverTimestamp()},{merge:true});return{success:true}}
export async function getPreferences(req){const u=await requireUser(req),s=await getDb().collection("notificationPreferences").doc(u.uid).get();return{preferences:{inApp:true,transactionalEmail:true,whatsapp:false,telegram:false,targetReminders:true,resourceNotifications:true,classNotifications:true,expiryReminders:true,marketing:false,...(s.exists?s.data():{})},providers:providerStatus()}}
export async function savePreferences(req,b={}){const u=await requireUser(req);const p={inApp:true,transactionalEmail:b.transactionalEmail!==false,whatsapp:false,telegram:false,targetReminders:b.targetReminders!==false,resourceNotifications:b.resourceNotifications!==false,classNotifications:b.classNotifications!==false,expiryReminders:b.expiryReminders!==false,marketing:Boolean(b.marketing),uid:u.uid,source:"student_desk",consentUpdatedAt:serverTimestamp(),updatedAt:serverTimestamp()};await getDb().collection("notificationPreferences").doc(u.uid).set(p,{merge:true});return{preferences:p}}
export async function listAdminNotifications(admin,q={}){if(!admin?.permissions?.includes("notifications.view")&&admin?.role!=="super_admin")fail(403,"Permission denied.");const snap=await getDb().collection("notifications").limit(250).get();let items=snap.docs.map(d=>({...safe(d.id,d.data()),recipientEmail:d.data().recipientEmail||"",recipientUid:d.data().recipientUid||"",idempotencyKey:d.data().idempotencyKey||""})).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const search=clean(q.q||q.search,120).toLowerCase();if(search)items=items.filter(x=>JSON.stringify(x).toLowerCase().includes(search));if(q.eventType)items=items.filter(x=>x.eventType===q.eventType);if(q.status)items=items.filter(x=>Object.values(x.channels).some(c=>c.state===q.status));const page=Math.max(1,Number(q.page)||1),pageSize=Math.min(q.exportAll===true?250:50,Math.max(10,Number(q.pageSize)||20)),total=items.length;return{notifications:{items:items.slice((page-1)*pageSize,page*pageSize),total,page,pageSize,hasMore:page*pageSize<total},providers:providerStatus()}}
export async function getAdminNotification(admin,id){const r=await listAdminNotifications(admin,{pageSize:250,exportAll:true}),item=r.notifications.items.find(x=>x.id===clean(id,200));if(!item)fail(404,"Notification not found.");const d=await getDb().collection("notificationDeliveries").where("notificationId","==",item.id).limit(20).get();return{notification:item,deliveries:d.docs.map(x=>{const value=x.data();return{id:x.id,...value,recipientEmail:value.channel==="email"?maskEmail(value.recipientEmail):"",queuedAt:iso(value.queuedAt),failedAt:iso(value.failedAt),sentAt:iso(value.sentAt),deliveredAt:iso(value.deliveredAt),lastAttemptedAt:iso(value.lastAttemptedAt),updatedAt:iso(value.updatedAt),nextRetryAt:iso(value.nextRetryAt)}}),providers:r.providers}}
function maskEmail(value){const [local,domain]=String(value||"").split("@");return local&&domain?`${local.slice(0,2)}***@${domain}`:""}
export async function retryDelivery(admin,notificationId,channel){if(!admin?.permissions?.includes("notifications.manage")&&admin?.role!=="super_admin")fail(403,"Permission denied.");if(channel!=="email")fail(409,"This provider is not available for retry.");const config=providerStatus().email;if(!config.enabled)fail(409,"Provider configuration is required before retry.");const detail=await getAdminNotification(admin,notificationId),delivery=detail.deliveries.find(item=>item.channel==="email");if(!delivery)fail(404,"Delivery record not found.");if(Number(delivery.attemptNumber||0)>=MAX_ATTEMPTS)fail(409,"Maximum delivery attempts reached.");if(!RETRYABLE.has(delivery.status))fail(409,"This delivery is not currently retryable.");if(delivery.nextRetryAt&&new Date(delivery.nextRetryAt).getTime()>Date.now())fail(409,"The delivery backoff period has not passed.");const result=await deliverNotificationEmail(notificationId,{allowedStatuses:[delivery.status]});if(result.status==="not_claimed")fail(409,"This delivery is already being processed.");if(detail.notification.related?.enquiryId){const enquiryRef=getDb().collection("contactEnquiries").doc(detail.notification.related.enquiryId),enquirySnap=await enquiryRef.get();if(enquirySnap.exists){const conversation=(enquirySnap.data().conversation||[]).map(reply=>reply.notificationId===notificationId?{...reply,deliveryStatus:result.status,providerMessageId:result.providerMessageId||reply.providerMessageId||"",safeFailureCode:"",safeFailureMessage:""}:reply);await enquiryRef.set({conversation,updatedAt:serverTimestamp()},{merge:true})}}await writeAdminActivityLog({admin,action:"notification.delivery.retry",entityType:"notificationDelivery",entityId:result.deliveryId,safeMetadata:{notificationId:detail.notification.id,channel,attemptNumber:Number(delivery.attemptNumber||0)+1,result:result.status}});return result}
function csvCell(value){const t=String(value??"").replaceAll(String.fromCharCode(13)," ").replaceAll(String.fromCharCode(10)," ");const valueSafe="=+-@".includes(t.charAt(0))?"'"+t:t;return JSON.stringify(valueSafe)}
export async function exportAdminNotifications(admin,q={}){const result=await listAdminNotifications(admin,{...q,page:1,pageSize:250,exportAll:true});const rows=[];for(const n of result.notifications.items){for(const channel of Object.keys(n.channels||{})){const c=n.channels[channel]||{};rows.push({notificationId:n.id,recipientName:"",recipientEmail:n.recipientEmail,eventType:n.eventType,title:n.title,relatedPlan:n.related?.planId||"",relatedOrderId:n.related?.orderId||"",relatedSubscriptionId:n.related?.subscriptionId||"",createdAt:n.createdAt,readStatus:n.readAt?"read":"unread",channel,deliveryStatus:c.state||"",retryCount:c.retryCount||0,safeFailureCode:c.safeFailureCode||""})}}const headers=Object.keys(rows[0]||{notificationId:"",recipientName:"",recipientEmail:"",eventType:"",title:"",relatedPlan:"",relatedOrderId:"",relatedSubscriptionId:"",createdAt:"",readStatus:"",channel:"",deliveryStatus:"",retryCount:"",safeFailureCode:""});return{filename:"notification-export-"+new Date().toISOString().slice(0,10)+".csv",contentType:"text/csv; charset=utf-8",body:[headers.map(csvCell).join(","),...rows.map(r=>headers.map(h=>csvCell(r[h])).join(","))].join(String.fromCharCode(10))}}
export async function createTestNotification(admin,body={}){if(admin?.role!=="super_admin")fail(403,"Super-admin access required.");if(process.env.ENABLE_TEST_NOTIFICATIONS!=="true")fail(403,"Test notifications are disabled.");if(body.confirmation!=="CREATE TEST NOTIFICATION")fail(400,"Type CREATE TEST NOTIFICATION to confirm.");const runId=clean(body.testRunId,100),uid=clean(body.recipientUid,200),recipientEmail=clean(body.recipientEmail||admin.email,254);if(!runId||!uid||!isValidEmail(recipientEmail))fail(400,"Recipient UID, email, and test-run ID are required.");const id=await createNotification({eventType:"test_notification",uid,email:recipientEmail,title:"Test notification",message:"This is an authorized Delight Banking delivery test.",destination:"/student-desk/notifications",idempotencyKey:"test:"+uid+":"+runId,templateData:{studentName:clean(body.recipientName,120)||"Student"}});await writeAdminActivityLog({admin,action:"notification.test.create",entityType:"notification",entityId:id,safeMetadata:{recipientUid:uid,testRunId:runId}});return{notificationId:id,deliveryId:docId(id+":email")}}