import crypto from "node:crypto";
import { getDb, serverTimestamp } from "./firebaseAdmin.js";

const API_ROOT = "https://api.telegram.org";
const MAX_ATTEMPTS = 5;
const TRANSACTIONAL = new Set(["payment_successful","payment_failed","payment_cancelled","payment_pending","subscription_activated","subscription_granted","subscription_extended","subscription_expiring_7_days","subscription_expiring_3_days","subscription_expiring_1_day","subscription_expired"]);
function clean(value,max=500){return String(value||"").trim().slice(0,max)}
function fail(statusCode,message,code="TELEGRAM_ERROR"){const error=new Error(message);error.statusCode=statusCode;error.code=code;throw error}
function hash(value){return crypto.createHash("sha256").update(String(value)).digest("hex")}
function hmac(value,secret=process.env.TELEGRAM_CONNECTION_SECRET||""){return crypto.createHmac("sha256",secret).update(String(value)).digest("hex")}
function tokenSignature(value,secret){return crypto.createHmac("sha256",secret).update(String(value)).digest("base64url").slice(0,32)}
function iso(value){return value?.toDate?value.toDate().toISOString():value instanceof Date?value.toISOString():value||null}
function secureEqual(left,right){const a=Buffer.from(String(left)),b=Buffer.from(String(right));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
export function telegramConfigured(){return Boolean(process.env.TELEGRAM_BOT_TOKEN&&process.env.TELEGRAM_BOT_USERNAME&&process.env.TELEGRAM_CONNECTION_SECRET)}
export function telegramWebhookSecret(secret=process.env.TELEGRAM_CONNECTION_SECRET||""){return hmac("delight-guidance-telegram-webhook",secret)}
export function createSignedConnectionToken(secret=process.env.TELEGRAM_CONNECTION_SECRET||""){if(!secret)throw new Error("Telegram connection secret is unavailable.");const value=crypto.randomBytes(16).toString("base64url");return value+"."+tokenSignature(value,secret)}
export function verifySignedConnectionToken(token,secret=process.env.TELEGRAM_CONNECTION_SECRET||""){const parts=String(token||"").split(".");return Boolean(secret)&&parts.length===2&&parts[0].length>=20&&secureEqual(parts[1],tokenSignature(parts[0],secret))}
export function isTelegramWebhookSecretValid(supplied,secret=process.env.TELEGRAM_CONNECTION_SECRET||""){return Boolean(secret)&&secureEqual(supplied,telegramWebhookSecret(secret))}
export function isConnectionTokenRecordUsable(record,now=Date.now()){const expiry=record?.expiresAt?.toDate?record.expiresAt.toDate():new Date(record?.expiresAt||0);return Boolean(record?.uid&&!record?.usedAt&&!Number.isNaN(expiry.getTime())&&expiry.getTime()>=now)}
export function telegramPreferenceAllowed(eventType,preferences={}){return eventType==="announcement"?preferences.marketing===true&&preferences.telegram===true:TRANSACTIONAL.has(eventType)?preferences.telegram!==false:preferences.telegram===true}
export function escapeTelegramHtml(value){return String(value??"").replace(/[&<>]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[char]))}
export function classifyTelegramFailure(status=0,description="",parameters={}){const message=String(description||"").toLowerCase();if(Number(status)===429)return{retryable:true,status:"failed",retryAfter:Math.min(Math.max(Number(parameters.retry_after)||60,1),3600)};if(message.includes("bot was blocked")||message.includes("user is deactivated")||message.includes("chat not found"))return{retryable:false,status:"permanent_failure",disconnect:true};if(Number(status)===401||message.includes("unauthorized"))return{retryable:false,status:"configuration_required"};if(Number(status)>=500||Number(status)===0)return{retryable:true,status:"failed",retryAfter:60};return{retryable:false,status:"permanent_failure"}}
function maskedChat(chatId){const value=String(chatId||"");return value.length>4?"***"+value.slice(-4):"***"}
function deliveryId(notificationId){return hash(notificationId+":telegram")}
async function botRequest(method,payload,{fetchImpl=fetch,timeoutMs=8000}={}){
 if(!telegramConfigured())return{ok:false,httpStatus:503,description:"Telegram provider configuration is required.",errorCode:"CONFIGURATION_REQUIRED"};
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);
 try{const response=await fetchImpl(API_ROOT+"/bot"+process.env.TELEGRAM_BOT_TOKEN+"/"+method,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),signal:controller.signal});const data=await response.json().catch(()=>({}));return{...data,httpStatus:response.status}}
 catch(error){return{ok:false,httpStatus:0,description:error?.name==="AbortError"?"Telegram provider request timed out.":"Telegram provider network request failed.",errorCode:error?.name==="AbortError"?"PROVIDER_TIMEOUT":"PROVIDER_NETWORK_ERROR"}}
 finally{clearTimeout(timer)}
}
export async function createTelegramConnectionLink(user){
 if(!telegramConfigured())fail(503,"Telegram connection is not configured.","CONFIGURATION_REQUIRED");
 const token=createSignedConnectionToken(),value=token.split(".")[0],tokenHash=hash(value),expiresAt=new Date(Date.now()+10*60*1000);
 await getDb().collection("telegramConnectionTokens").doc(tokenHash).set({uid:user.uid,expiresAt,usedAt:null,createdAt:serverTimestamp()});
 return{url:"https://t.me/"+clean(process.env.TELEGRAM_BOT_USERNAME,80)+"?start="+encodeURIComponent(token),expiresAt:expiresAt.toISOString(),bot:"@"+clean(process.env.TELEGRAM_BOT_USERNAME,80)}
}
export async function telegramConnectionStatus(uid){
 const snap=await getDb().collection("telegramConnections").doc(clean(uid,240)).get();const value=snap.exists?snap.data():{};
 return{connected:Boolean(snap.exists&&value.active),status:snap.exists&&value.active?"connected":"not_connected",bot:"@"+clean(process.env.TELEGRAM_BOT_USERNAME||"DelightGuidanceBot",80),chat: value.active?maskedChat(value.chatId):""}
}
export async function disconnectTelegram(user){
 const ref=getDb().collection("telegramConnections").doc(user.uid),snap=await ref.get();if(snap.exists){const chatHash=snap.data().chatHash,batch=getDb().batch();batch.set(ref,{active:false,disconnectedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});if(chatHash)batch.set(getDb().collection("telegramChatLinks").doc(chatHash),{active:false,updatedAt:serverTimestamp()},{merge:true});await batch.commit()}
 await getDb().collection("notificationPreferences").doc(user.uid).set({telegram:false,updatedAt:serverTimestamp()},{merge:true});return{connection:await telegramConnectionStatus(user.uid)}
}
async function connectChat(token,chat){
 if(!verifySignedConnectionToken(token))return{connected:false};
 const value=token.split(".")[0],tokenRef=getDb().collection("telegramConnectionTokens").doc(hash(value)),chatId=String(chat.id),chatHash=hash(chatId),connectionResult={connected:false};
 await getDb().runTransaction(async tx=>{const tokenSnap=await tx.get(tokenRef);if(!tokenSnap.exists)return;const tokenData=tokenSnap.data();if(!isConnectionTokenRecordUsable(tokenData))return;const linkRef=getDb().collection("telegramChatLinks").doc(chatHash),linkSnap=await tx.get(linkRef);if(linkSnap.exists&&linkSnap.data().active&&linkSnap.data().uid!==tokenData.uid)return;const connectionRef=getDb().collection("telegramConnections").doc(tokenData.uid),previous=await tx.get(connectionRef);if(previous.exists&&previous.data().active&&previous.data().chatHash!==chatHash)return;tx.set(tokenRef,{usedAt:serverTimestamp(),chatHash},{merge:true});tx.set(linkRef,{uid:tokenData.uid,active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});tx.set(connectionRef,{uid:tokenData.uid,chatId,chatHash,active:true,telegramUserId:String(chat.id),username:clean(chat.username,80),connectedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});tx.set(getDb().collection("notificationPreferences").doc(tokenData.uid),{telegram:true,updatedAt:serverTimestamp()},{merge:true});connectionResult.connected=true});
 return connectionResult;
}
export async function handleTelegramWebhook(req){
 if(req.method!=="POST")fail(405,"Method not allowed.","METHOD_NOT_ALLOWED");
 if(!telegramConfigured())fail(503,"Telegram configuration is unavailable.","CONFIGURATION_REQUIRED");
 const supplied=String(req.headers["x-telegram-bot-api-secret-token"]||"");if(!isTelegramWebhookSecretValid(supplied))fail(401,"Invalid Telegram webhook secret.","INVALID_WEBHOOK_SECRET");
 const update=req.body&&typeof req.body==="object"?req.body:{};if(Buffer.byteLength(JSON.stringify(update))>64*1024)fail(413,"Telegram update is too large.","PAYLOAD_TOO_LARGE");
 const message=update.message;if(!message||message.chat?.type!=="private"||typeof message.text!=="string")return{ok:true,ignored:true};
 const command=message.text.trim();
 if(command.startsWith("/start")){const token=command.split(" ").filter(Boolean)[1]||"",result=await connectChat(token,message.chat),lineBreak=String.fromCharCode(10);if(result.connected)await botRequest("sendMessage",{chat_id:message.chat.id,text:String.fromCharCode(9989)+" Telegram notifications connected"+lineBreak+lineBreak+"Your Delight Guidance account is now connected to this Telegram chat. You can receive payment, subscription and Student Desk updates here."});else await botRequest("sendMessage",{chat_id:message.chat.id,text:"This connection link is invalid, expired, already used, or belongs to an account that cannot be connected. Generate a new link in Delight Guidance notification settings."});return{ok:true}}
 if(command.startsWith("/help")){await botRequest("sendMessage",{chat_id:message.chat.id,text:"Use /start with the secure link from your Delight Guidance notification settings. For help, email support@delightguidance.com."});return{ok:true}}
 if(command.startsWith("/settings")){await botRequest("sendMessage",{chat_id:message.chat.id,text:"Manage or disconnect Telegram notifications at https://www.delightguidance.com/student-desk/notification-settings"});return{ok:true}}
 return{ok:true,ignored:true}
}export async function getTelegramEligibility(uid,eventType){
 if(!telegramConfigured())return{enabled:false,status:"configuration_required"};const connection=await telegramConnectionStatus(uid);if(!connection.connected)return{enabled:false,status:"not_connected"};const prefSnap=await getDb().collection("notificationPreferences").doc(uid).get(),preferences=prefSnap.exists?prefSnap.data():{};const allowed=telegramPreferenceAllowed(eventType,preferences);if(!allowed)return{enabled:false,status:"suppressed"};return{enabled:true,status:"queued"}
}
function telegramText(notification){
 const data=notification.templateData||{},lines=["<b>"+escapeTelegramHtml(notification.title||"Delight Banking update")+"</b>",escapeTelegramHtml(notification.message||"")];if(data.planName)lines.push("<b>Plan:</b> "+escapeTelegramHtml(data.planName));if(data.durationLabel)lines.push("<b>Duration:</b> "+escapeTelegramHtml(data.durationLabel));if(data.amount)lines.push("<b>Amount:</b> "+escapeTelegramHtml(String(data.amount)+" "+(data.currency||"INR")));if(data.orderId)lines.push("<b>Order ID:</b> "+escapeTelegramHtml(data.orderId));if(data.accessStartAt)lines.push("<b>Starts:</b> "+escapeTelegramHtml(String(data.accessStartAt)));if(data.accessEndAt)lines.push("<b>Access ends:</b> "+escapeTelegramHtml(String(data.accessEndAt)));const destination=String(notification.destination||"/student-desk").startsWith("/")&&!String(notification.destination||"").startsWith("//")?notification.destination:"/student-desk";lines.push('<a href="https://www.delightguidance.com'+escapeTelegramHtml(destination)+'">Open Student Desk</a>');return lines.filter(Boolean).join(String.fromCharCode(10)+String.fromCharCode(10))
}async function claim(notificationId,allowedStatuses){
 const ref=getDb().collection("notificationDeliveries").doc(deliveryId(notificationId));let claimed=null;await getDb().runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)return;const value=snap.data(),attempt=Number(value.attemptNumber||0);if(!allowedStatuses.includes(value.status)||attempt>=MAX_ATTEMPTS)return;claimed={...value,attemptNumber:attempt+1};tx.set(ref,{status:"processing",attemptNumber:attempt+1,lastAttemptedAt:serverTimestamp(),nextRetryAt:null,safeFailureCode:"",safeFailureMessage:"",updatedAt:serverTimestamp()},{merge:true})});return claimed
}
async function finalize(notificationId,attempt,result){
 const deliveryRef=getDb().collection("notificationDeliveries").doc(deliveryId(notificationId)),notificationRef=getDb().collection("notifications").doc(notificationId),update={status:result.status,providerMessageId:clean(result.messageId,100),safeProviderResponse:result.safeProviderResponse||{},safeFailureCode:clean(result.code,100),safeFailureMessage:clean(result.message,500),nextRetryAt:result.nextRetryAt||null,updatedAt:serverTimestamp()};if(["sent","accepted"].includes(result.status))update.sentAt=serverTimestamp();else update.failedAt=serverTimestamp();const batch=getDb().batch();batch.set(deliveryRef,update,{merge:true});batch.set(notificationRef,{["channels.telegram.state"]:result.status,["channels.telegram.retryCount"]:attempt,["channels.telegram.safeFailureCode"]:update.safeFailureCode},{merge:true});await batch.commit()
}
export async function deliverNotificationTelegram(notificationId,{allowedStatuses=["queued"],fetchImpl=fetch}={}){
 if(!telegramConfigured())return{status:"configuration_required",deliveryId:deliveryId(notificationId)};const claimed=await claim(notificationId,allowedStatuses);if(!claimed)return{status:"not_claimed",deliveryId:deliveryId(notificationId)};const notificationSnap=await getDb().collection("notifications").doc(notificationId).get();if(!notificationSnap.exists){await finalize(notificationId,claimed.attemptNumber,{status:"permanent_failure",code:"NOTIFICATION_NOT_FOUND",message:"Notification record is unavailable."});return{status:"permanent_failure",deliveryId:deliveryId(notificationId)}}const notification={id:notificationSnap.id,...notificationSnap.data()},connection=await getDb().collection("telegramConnections").doc(notification.recipientUid).get();if(!connection.exists||!connection.data().active){await finalize(notificationId,claimed.attemptNumber,{status:"not_connected",code:"NOT_CONNECTED",message:"Telegram is not connected."});return{status:"not_connected",deliveryId:deliveryId(notificationId)}}const chatId=connection.data().chatId,result=await botRequest("sendMessage",{chat_id:chatId,text:telegramText(notification),parse_mode:"HTML",disable_web_page_preview:true},{fetchImpl});if(result.ok){await finalize(notificationId,claimed.attemptNumber,{status:"sent",messageId:result.result?.message_id,safeProviderResponse:{accepted:true,chat:maskedChat(chatId)}});return{status:"sent",deliveryId:deliveryId(notificationId),providerMessageId:clean(result.result?.message_id,100)}}const classification=classifyTelegramFailure(result.httpStatus,result.description,result.parameters),atLimit=claimed.attemptNumber>=MAX_ATTEMPTS;if(classification.disconnect){await getDb().collection("telegramConnections").doc(notification.recipientUid).set({active:false,disconnectedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})}const nextRetryAt=classification.retryable&&!atLimit?new Date(Date.now()+classification.retryAfter*1000):null,status=atLimit?"permanent_failure":classification.status;await finalize(notificationId,claimed.attemptNumber,{status,code:result.errorCode||String(result.error_code||"TELEGRAM_ERROR"),message:result.description||"Telegram rejected the message.",nextRetryAt,safeProviderResponse:{httpStatus:Number(result.httpStatus)||0}});return{status,deliveryId:deliveryId(notificationId)}
}
export async function manageTelegramWebhook(admin,action,{fetchImpl=fetch}={}){
 if(admin?.role!=="super_admin")fail(403,"Super-admin access required.","PERMISSION_DENIED");const url="https://www.delightguidance.com/api/student-content?resource=telegram_webhook";
 if(action==="register"){const commands=await botRequest("setMyCommands",{commands:[{command:"start",description:"Connect Delight Guidance notifications"},{command:"help",description:"Show help and support information"},{command:"settings",description:"Manage notification settings"}]},{fetchImpl});if(!commands.ok)return{status:"telegram_api_error",url};const result=await botRequest("setWebhook",{url,secret_token:telegramWebhookSecret(),allowed_updates:["message"],drop_pending_updates:false},{fetchImpl});return{status:result.ok?"configured":"telegram_api_error",url}}
 const result=await botRequest("getWebhookInfo",{}, {fetchImpl});if(!result.ok)return{status:"telegram_api_error",url};return{status:result.result?.url===url?"configured":result.result?.url?"incorrect_url":"not_configured",url,pendingUpdateCount:Number(result.result?.pending_update_count||0),lastError:clean(result.result?.last_error_message,300)}
}